server:
  port: 8080

spring:
    datasource:
        name: join
        url: jdbc:mysql://127.0.0.1:3306/join
        username: root
        password: root
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        #配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        #超过时间限制是否回收 
        removeAbandoned: true
        #超时时间；单位为秒
        removeAbandonedTimeout: 1800
        #关闭abanded连接时输出错误日志
        logAbandoned: true
    #邮箱配置    
    mail:
        host: smtp.exmail.qq.com #邮箱地址
        username: zhangliang@qk365.com #登录用户
        password: lzhang123
        default-encoding: UTF-8
        fromMail:
          addr: zhangliang@qk365.com
    #redis配置
    redis:
      database: 0 # Redis数据库索引（默认为0）
      host: 127.0.0.1 # Redis服务器地址
      password: 
      port: 6379
      pool:
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
        max-active: 1024 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      timeout: 1000 # 连接超时时间（毫秒）
      block-when-exhausted: true

mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zl.spbm.entity

#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
