server:
  port: 8080

spring:
  application:
    name: spbm

  datasource:
    name: join
    url: jdbc:mysql://127.0.0.1:3306/join
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      filters: stat
      max-active: 20
      initial-size: 1
      max-wait: 60000
      min-idle: 1
      timeBetweenEvictionRunsMillis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 30000 #配置一个连接在池中最小生存的时间，单位是毫秒
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      test-on-return: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
      removeAbandoned: true #超过时间限制是否回收
      removeAbandonedTimeout: 1800 #超时时间；单位为秒
      logAbandoned: true #关闭Abandoned连接时输出错误日志

  #邮箱配置
  mail:
    host: smtp.exmail.qq.com #邮箱地址
    username: zhangliang@qk365.com #登录用户
    password: Lzhang123
    default-encoding: UTF-8
    fromMail:
      addr: zhangliang@qk365.com


  #redis配置-sentinel
  redis:
    pool:
      max-idle: 100 # 连接池中的最大空闲连接
      min-idle: 10 # 连接池中的最小空闲连接
      max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 1000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
    sentinel:
      master: mymaster
      nodes: 127.0.0.1:26379,127.0.0.1:26479,127.0.0.1:26579
  redisson:
    address: 127.0.0.1:6379



mybatis:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  type-aliases-package: com.zl.spbm.entity

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql